name: Packer

on:
  push:
    branches:
      - main

env:
  IMAGE_PUBLISHER: MicrosoftWindowsDesktop

  # With Office 365
  IMAGE_OFFER: office-365
  IMAGE_SKU: win11-21h2-avd-m365

  # Without Office 365
  #IMAGE_OFFER: windows-11
  #IMAGE_SKU: win11-21h2-avd

jobs:
  latest_windows_version:
    name: Get latest available Windows version from Azure
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.az_vm_image_version.outputs.version }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Query Latest Version
        id: az_vm_image_version
        uses: azure/CLI@v1
        with:
          azcliversion: 2.34.0
          inlineScript: |
            latest_version=$(
              az vm image list \
                --publisher "${IMAGE_PUBLISHER}" \
                --offer "${IMAGE_OFFER}" \
                --sku "${IMAGE_SKU}" \
                --all \
                --query "[*].version | sort(@)[-1:]" \
                --out tsv
            )

            echo "Publisher: ${IMAGE_PUBLISHER}"
            echo "Offer:     ${IMAGE_OFFER}"
            echo "SKU:       ${IMAGE_SKU}"
            echo "Version:   ${latest_version}"

            echo "::set-output name=version::${latest_version}"

  check_if_image_exists:
    name: Check if latest version has already been built
    runs-on: ubuntu-latest
    needs: latest_windows_version
    outputs:
      image_exists: ${{ steps.az_image_exists.outputs.image_exists }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Check If Image Exists
        id: az_image_exists
        uses: azure/CLI@v1
        with:
          azcliversion: 2.34.0
          inlineScript: |
            if az image show \
              --resource-group "${{ secrets.PACKER_ARTIFACTS_RESOURCE_GROUP }}" \
              --name "${IMAGE_SKU}-${{ needs.latest_windows_version.outputs.version }}"; then
              image_exists=true
            else
              image_exists=false
            fi

            echo "Image Exists: ${image_exists}"
            echo "::set-output name=image_exists::${image_exists}"

  packer:
    name: Packer
    runs-on: ubuntu-latest
    needs: [latest_windows_version, check_if_image_exists]
    if: needs.check_if_image_exists.outputs.image_exists == 'false'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: .

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: -color=false -on-error=abort
        env:
          PKR_VAR_client_id: ${{ secrets.PACKER_CLIENT_ID }}
          PKR_VAR_client_secret: ${{ secrets.PACKER_CLIENT_SECRET }}
          PKR_VAR_subscription_id: ${{ secrets.PACKER_SUBSCRIPTION_ID }}
          PKR_VAR_tenant_id: ${{ secrets.PACKER_TENANT_ID }}
          PKR_VAR_artifacts_resource_group: ${{ secrets.PACKER_ARTIFACTS_RESOURCE_GROUP }}
          PKR_VAR_build_resource_group: ${{ secrets.PACKER_BUILD_RESOURCE_GROUP }}
          PKR_VAR_source_image_publisher: ${IMAGE_PUBLISHER}
          PKR_VAR_source_image_offer: ${IMAGE_OFFER}
          PKR_VAR_source_image_sku: ${IMAGE_SKU}
          PKR_VAR_source_image_version: ${{ needs.latest_windows_version.outputs.version }}
