name: Packer

on:
  push:
    branches:
      - main

env:
  IMAGE_PUBLISHER: MicrosoftWindowsDesktop

  # With Office 365
  IMAGE_OFFER: office-365
  IMAGE_SKU: win11-21h2-avd-m365

  # Without Office 365
  #IMAGE_OFFER: windows-11
  #IMAGE_SKU: win11-21h2-avd

jobs:
  latest_windows_version:
    name: Get Latest Windows Version Available on Azure
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.az_vm_image_version.outputs.version }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Query Version
        id: az_vm_image_version
        uses: azure/CLI@v1
        with:
          azcliversion: 2.34.0
          inlineScript: |
            latest_version=$(
              az vm image list \
                --publisher "${IMAGE_PUBLISHER}" \
                --offer "${IMAGE_OFFER}" \
                --sku "${IMAGE_SKU}" \
                --all \
                --query "[*].version | sort(@)[-1:]" \
                --out tsv
            )

            echo "Publisher: ${IMAGE_PUBLISHER}"
            echo "Offer:     ${IMAGE_OFFER}"
            echo "SKU:       ${IMAGE_SKU}"
            echo "Version:   ${latest_version}"

            echo "::set-output name=version::${latest_version}"

  packer_build:
    name: Packer Build
    runs-on: ubuntu-latest
    needs: latest_windows_version
    steps:
      - name: Print Windows Version
        run: echo ${{ needs.latest_windows_version.outputs.version }}
